URL_FIRST_PART = 'http://houseplantshop.com'
URL_SECOND_PART_FIRST_TIME = '/collections/all-products?'
URL_PAGE_TAG = '?page=1&grid_list=grid-view'
ATTEMPTS = 3
WAIT_TIME = 5
CHARACTERS_TO_STRIP = '\n '
CURRENCY_SIGN = '$'
HAS_OPTIONS = 'from'
NO_PRICE = 0
IGNORE = 3
COLON = ':'
NOT_FOUND = -1
NEW_LINE = '\n'
SEPARATOR = ' - '
ANOTHER_SEPARATOR = ' / '
FIRST = 0
LAST = -1
BATCH_SIZE = 10
FEATURE_INDEX = 0
URL_INDEX = 1
PAGES_INDICATOR_INDEX = -2
PRODUCT_INDEX = 2
LOWER = 0
HIGHER = 1
BY = 0
ORDER = 1
BEGINNING = 1
END = -1
FEATURE = 1
PRODUCT = 2
MAX_COLUMN_WIDTH = 80
FEATURE_DIVIDER_LENGTH = 160
PRODUCT_DIVIDER_LENGTH = 100

# db_func.py variables
NAME_INDEX = 0
TYPE_INDEX = 1
OPTION_INDEX = 2

SQL_PASS = 'Ineedajob1!'
SQL_HOST = 'localhost'
SQL_USER = 'root'
SQL_DB = 'plant_db'
SQL_CHARSET = 'utf8mb4'
